import { Deadlinejs } from "@/types/deadlinejs";

export const generateDeadlinejsCode = (data: Deadlinejs, bypassDeadline = false) => {
    return `// THIS CODE IS GENERATED BY SNBT MIRROR
const snbt_current_time = '${bypassDeadline ? data.snbtCurrentTime : data.snbtDeadlineTime}';${bypassDeadline ? '// BYPASSED' : ''}
const snbt_deadline_time = '${data.snbtDeadlineTime}';
const deadline_status = '${data.snbtDeadlineStatus}';
const dataurl = \`${data.snbtDataUrl}\`;
    `.trim();
}